// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9jfrveliGgODAjkKY3U-Tn2XglFSK0xI',
    appId: '1:159189150744:web:c29f75f0d22493f8ac276d',
    messagingSenderId: '159189150744',
    projectId: 'nowaste-99c72',
    authDomain: 'nowaste-99c72.firebaseapp.com',
    storageBucket: 'nowaste-99c72.firebasestorage.app',
    measurementId: 'G-PVJ62BZ2G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiE4gw6gW_jx5l2OLhUeDGueLUW62rZmM',
    appId: '1:67656538715:android:81b2a0738aa5ba18abbd7e',
    messagingSenderId: '67656538715',
    projectId: 'duplicatebuildpro',
    storageBucket: 'duplicatebuildpro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUJifBuHjkYLds3B1T-qaOYIm5nLJVx7M',
    appId: '1:67656538715:ios:a29e95a95efdccb6abbd7e',
    messagingSenderId: '67656538715',
    projectId: 'duplicatebuildpro',
    storageBucket: 'duplicatebuildpro.firebasestorage.app',
    iosBundleId: 'com.duplicatebuildingsolution.duplicateBuildingSolution',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcLXrxKEoTu9PDuAZ1XzUN4LuGYHzrem0',
    appId: '1:159189150744:ios:415174562d7ad05cac276d',
    messagingSenderId: '159189150744',
    projectId: 'nowaste-99c72',
    storageBucket: 'nowaste-99c72.firebasestorage.app',
    iosBundleId: 'com.buildingSolution.buildingSolution',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9jfrveliGgODAjkKY3U-Tn2XglFSK0xI',
    appId: '1:159189150744:web:8b538c31724a7b78ac276d',
    messagingSenderId: '159189150744',
    projectId: 'nowaste-99c72',
    authDomain: 'nowaste-99c72.firebaseapp.com',
    storageBucket: 'nowaste-99c72.firebasestorage.app',
    measurementId: 'G-76056MK6KJ',
  );
}